### ISSUE TITLE
undefined cookie value

### ISSUE THREAD

**Issue by AndriiTsok** [amorey/edge-csrf#4]
I just tried to use the latest version of the library and noticed that the cookie value is not properly set. This results in the missing value of the csrf token.

next: 15.4.1

Please find screenshoots below:
Chrome:
<img width="434" alt="Screenshot 2022-12-27 at 7 14 10 PM" src="https://user-images.githubusercontent.com/733224/209738638-897ddafc-8d06-4c87-b7de-45139b6a5323.png">

Console:
<img width="623" alt="Screenshot 2022-12-27 at 7 16 25 PM" src="https://user-images.githubusercontent.com/733224/209738804-89e0ff8a-5990-4ad7-a9d1-ba19e8c61347.png">

Also, I noticed a warning from next: Middleware is returning a response body (line: 13), which is not supported.
Learn more: https://nextjs.org/docs/messages/returning-response-body-in-middleware

I hope my feedback helps! Thank you for your work on this library!

**Comment by AndriiTsok** [comment]
Error: A middleware can not alter response's body. Learn more: https://nextjs.org/docs/messages/returning-response-body-in-middleware

**Comment by AndriiTsok** [comment]
Just found the experimental parameter: allowMiddlewareResponseBody. 
That removed the warning, but the cookie values are not properly set.

**Comment by amorey** [comment]
Thanks for your note about the middleware response. I added a note to the README to help others who run into the same issue. They just enabled that feature by default in Next.js 13.1 so hopefully it won't be a problem in the future.

About the undefined cookie, I just checked again and it's working for me in Chrome with Next.js 13.0 and 13.1. Also, there are unit tests that check cookie response values (https://github.com/amorey/edge-csrf/blob/main/test/index.test.ts#L191-L236) and they're passing too so I'm not sure what the issue is. Can you describe your setup in more detail? Also, can you try the [example app](https://github.com/amorey/edge-csrf/tree/main/example-ts) to see if it's working there?

**Comment by amorey** [comment]
@AndriiTsok Just wanted to follow up - have you had a chance to look at this again? Let me know how to reproduce the problem so I can debug it.

**Comment by elisavet1818** [comment]
I'm facing the same issue. My cookie is **undefined** (same as the picture). Seems like the problem lays in these lines:

```
 if (secretStr === undefined) {
      secret = createSecret(config.secretByteLength)
      const cookie = Object.assign({value: utoa(secret)}, config.cookie);
      response.cookies.set(cookie);
 }

```
I believe it should be this way:

```
 if (secretStr === undefined) {
      secret = createSecret(config.secretByteLength)
      response.cookies.set(config.cookie.name,  utoa(secret) , config.cookie);
 }

```

Thank you in advance!

**Comment by amorey** [comment]
Thanks for providing more details about the problem! Which version of Next.js are you using? The code you highlighted should work in Next.js v13.1.0+ because `cookie` is an object like the one in the example [here](https://nextjs.org/docs/advanced-features/middleware#using-cookies) and, in addition, that code is unit tested [here](https://github.com/amorey/edge-csrf/blob/main/test/index.test.ts#L192-L201).

Is the problem intermittent? Any other info you can provide me would be very helpful in debugging this problem.

**Comment by elisavet1818** [comment]
Is the library supported in Next.js v12? If so, what version should I install?

**Comment by amorey** [comment]
Yes, version 0.2.2 works with Next.js v12: https://www.npmjs.com/package/edge-csrf/v/0.2.2

Let me know if that fixes the problem!

**Comment by elisavet1818** [comment]
That fixed my problem! Thank you!

**Comment by amorey** [comment]
Great! Let me know if you run into any other issues.
